name: Unit tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Run tests with coverage
        run: go test -v ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Run tests -race
        run: go test -v ./... -race

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3